server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:tfs}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

rp:
  mongo:
    uri: mongodb://mongodb:27017
  bts:
    tfs:
      service:
        url: ${rp.tfs.microservice.url}

spring:
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:tfs}
        prefer-ip-address: false
