server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:tfs}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

rp:
  mongo:
    uri: mongodb://mongodb:27017
  bts:
    tfs:
      service:
        url: ${rp.bts.tfs.service.url}
      server:
        url: ${rp.bts.tfs.server.url}
      project: ${rp.bts.tfs.project}

spring:
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:tfs}
        prefer-ip-address: false
